dataset_link: https://huggingface.co/datasets/haiduonghuynhle/UAV_VisLoc_dataset/resolve/main/UAV_VisLoc_dataset.zip

data_folder: data
raw_folder: raw
extract_folder: uav
zip_file_name: 06_folder.zip

tile_scales: [518, 1036, 1554]

train_folders: [6]
test_folders: [6]

drone_res_height: 518
drone_res_width: 1036

top_k: 10

seed: 42